# Copyright 2023 The Bazel Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Cut a release whenever a new tag is pushed to the repo.
name: Release

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: If set, publish this as a release candidate / prerelease version.
        type: boolean
        required: true

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create release archive
        id: create_archive
        run: .github/workflows/create_archive.sh
      - name: Release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          name: ${{ steps.create_archive.outputs.jsonnet_version }}
          tag_name: ${{ steps.create_archive.outputs.jsonnet_version }}
          prerelease: ${{ inputs.prerelease }}
          draft: true
          fail_on_unmatched_files: true
          files: jsonnet-*.tar.gz
